apiVersion: skaffold/v4beta11
kind: Config
metadata:
    name: ticketing
build:
    local:
        push: false
    artifacts:
        - image: mohamedaklamaash/k8sauthservice
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "auth/src/**/*.ts"
                    dest: .
        - image: mohamedaklamaash/k8sclient-ticketing
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - dest: .
                    src: "client/app/**/*.{js,ts,tsx,jsx}"
        - image: mohamedaklamaash/k8s-ticketing
          context: ticketservice
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "ticketservice/src/**/*.ts"
                    dest: .
        - image: mohamedaklamaash/k8sorderservice
          context: orderservice
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "orderservice/src/**/*.ts"
                    dest: .
        - image: mohamedaklamaash/expirationservice
          context: expirationservice
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "expirationservice/src/**/*.ts"
                    dest: .
        - image: mohamedaklamaash/paymentservice
          context: paymentservice
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "paymentservice/src/**/*.ts"
                    dest: .
manifests:
    rawYaml:
        - ./kubernetes/*

deploy:
    kubectl: {}
