apiVersion: apps/v1
kind: Deployment
metadata:
    name: order-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: order-dep
    template:
        metadata:
            labels:
                app: order-dep
        spec:
            containers:
                - name: ordercontainer1
                  image: mohamedaklamaash/k8sorderservice
                  env:
                      - name: NATS_URL
                        value: http://nats-service:4222
                      - name: NATS_CLUSTER_ID
                        value: ticketing
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: MONGO_URI
                        value: mongodb://order-mongo-srv:27017/order
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
    name: order-srv
spec:
    selector:
        app: order-dep
    ports:
        - port: 3000
          targetPort: 3000
          protocol: TCP
